version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=chordbreak
      - POSTGRES_PASSWORD=chordbreak
      - POSTGRES_DB=chordbreak
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
